apiVersion: batch.paddlepaddle.org/v1alpha1
kind: SampleSet
metadata:
  name: icdar2015
spec:
  # 数据缓存分区数
  partitions: 1
  source:
    # 数据源
    uri: bos://paddleflow-public.hkg.bcebos.com/icdar2015/
  secretRef:
    # 数据源的AK/SK
    name: icdar2015