# Copyright 2020 The Knative Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Cert-Manager
  - ../cert-manager/cert-manager/base
  - ../cert-manager/kubeflow-issuer/base
  # Istio
  - ../istio-1-9/istio-crds/base
  - ../istio-1-9/istio-namespace/base
  - ../istio-1-9/istio-install/base
  # OIDC Authservice
  - ../common/oidc-authservice/base
  # Dex
  - ../common/dex/overlays/istio
  # KNative
  - ../common/knative/knative-serving/overlays/gateways
  - ../knative/knative-eventing/base
  - ../istio-1-9/cluster-local-gateway/base
  # Kubeflow namespace
  - ../kubeflow-namespace/base
  # Kubeflow Roles
  - ../kubeflow-roles/base
  # Kubeflow Istio Resources
  - ../istio-1-9/kubeflow-istio-resources/base


  # Kubeflow Pipelines
  - ../pipeline-multi-user/upstream/env/platform-agnostic-multi-user
  # Central Dashboard
  - ../centraldashboard/upstream/overlays/istio
  # Admission Webhook
  - ../admission-webhook/upstream/overlays/cert-manager
  # Notebook Controller
  - ../jupyter/jupyter-web-app/upstream/overlays/istio
  # Jupyter Web App
  - ../jupyter/notebook-controller/upstream/overlays/kubeflow
  # Profiles + KFAM
  - ../profiles/upstream/overlays/kubeflow
  # Volumes Web App
  - ../volumes-web-app/upstream/overlays/istio


  # User namespace
  - ../user-namespace/base